#spring.datasource.jndi-name=java:jboss/datasources/CitilinkDS
#
## 2. JMS - ????????: ??????? JNDI, ????? ???????????? ? ???????? ?? TCP
## spring.jms.jndi-name=  <-- ???????? ?????? ??? ???????
#spring.activemq.broker-url=tcp://127.0.0.1:61616
#spring.activemq.user=user1
#spring.activemq.password=12345
#
## 3. STOMP (???????????? ? ??????? ????????)
#app.stomp.host=127.0.0.1
#app.stomp.port=61613
#app.stomp.login=user1
#app.stomp.pass=12345
#app.stomp.queue-name=jms.queue.CreditRequestsQueue
#
## 4. ??????
#spring.task.scheduling.pool.size=2
#app.eis.warehouse-jndi=java:/eis/WarehouseConnector
#camunda.bpm.enabled=false
#
##spring.jms.jndi-name=java:/ConnectionFactory
#spring.jms.pub-sub-domain=false
#
#
## ????????? JNDI-?????, ????? Spring ??????????? ?????? TCP-????? ????
#spring.jms.jndi-name=
spring.jms.jndi-name=java:/ConnectionFactory
spring.jms.pub-sub-domain=false

# ????????? ????????? ???????????? ???????? ??? ??????? ??????
camunda.bpm.enabled=false
camunda.bpm.auto-deployment-enabled=false
camunda.bpm.deployment-resource-pattern=