server.servlet.context-path=/citilink
spring.main.allow-bean-definition-overriding=true
org.springframework.boot.logging.LoggingSystem=none

# JNDI
spring.datasource.jndi-name=java:jboss/datasources/CitilinkDS

# settings of Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# turn off JTA on Spring Boot level
spring.jta.enabled=false

# force turn off JTA into Hibernate
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc
spring.jpa.properties.hibernate.resource.transaction.backend_strategy=jdbc

# solving problem with joinTransaction()
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
# prohibit Hibernate from trying to use the server's transaction manager
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Swagger and Jackson
app.swagger.enabled=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration,\
org.springdoc.webmvc.ui.SwaggerConfig,\
org.springdoc.webmvc.core.configuration.SpringDocWebMvcConfiguration