server.servlet.context-path=/citilink
spring.main.allow-bean-definition-overriding=true
#org.springframework.boot.logging.LoggingSystem=none
# ?????? ????? ????????? Spring ???????? ???? ? ??????? WildFly
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.camunda.bpm=INFO

# JNDI ? ??
spring.datasource.jndi-name=java:jboss/datasources/CitilinkDS
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?????????? (JDBC ????? ??? ???????? ?? WildFly)
spring.jta.enabled=false
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc
spring.jpa.properties.hibernate.resource.transaction.backend_strategy=jdbc
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.wildfly.jpa.analyze=false

# Camunda
camunda.bpm.database.schema-update=true
camunda.bpm.job-execution.enabled=true
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
# ????????? Camunda ???????????? slf4j (??????? WildFly ?????? ????? ?????)
camunda.bpm.jpa.enabled=false

# ?????????? ???????????????? (????? ???????)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration,org.springdoc.webmvc.ui.SwaggerConfig,org.springdoc.webmvc.core.configuration.SpringDocWebMvcConfiguration

# ActiveMQ ? STOMP
spring.jms.jndi-name=java:/JmsXA
app.stomp.host=127.0.0.1
app.stomp.port=61713
app.stomp.queue-name=jms.queue.CreditRequestsQueue
app.eis.warehouse-jndi=java:/eis/WarehouseConnector
# ????????? JTA, ??? ??? ?????????? JDBC ?????????? ?????? Spring

# ?????????? ????? Spring ? Hibernate 6 (?????????? ?????? ??? Jakarta EE)
spring.jpa.properties.hibernate.resource.beans.container=org.springframework.orm.jpa.vendor.SpringBeanContainer
spring.jpa.properties.hibernate.cdi.extensions=false



# ????????? ??????? ????????? Jersey (?????? ???????? FATAL)
#spring.jersey.init.jersey.config.server.resource.validation.ignoreErrors=true
#spring.jersey.init.jersey.config.server.wadl.disableXmlAttributeValidation=true

# ????????? Jersey ???????????? ???????????? ?????? ?????? Camunda
#spring.jersey.init.jersey.config.server.provider.packages=org.camunda.bpm.engine.rest

# ??? ??????? Jersey (??????? ??? servlet, ??? ?????????? ? WildFly)
#spring.jersey.type=servlet
#spring.jersey.application-path=/engine-rest



#spring.jersey.type=filter

# ??????? ??? ??????:
# spring.jersey.init.jersey.config.server.resource.validation.ignoreErrors=true
# spring.jersey.init.jersey.config.server.wadl.disableXmlAttributeValidation=true
# spring.jersey.init.jersey.config.server.provider.packages=org.camunda.bpm.engine.rest
# spring.jersey.type=servlet (??? filter)
# spring.jersey.application-path=/engine-rest