spring.task.scheduling.pool.size=2

app.eis.warehouse-jndi=java:/eis/WarehouseConnector

app.stomp.host=localhost
app.stomp.port=61614
app.stomp.queue-name=jms.queue.CreditRequestsQueue

app.stomp.login=admin
app.stomp.pass=admin

