#spring.datasource.jndi-name=java:jboss/datasources/CitilinkDS
#spring.jms.jndi-name=java:/JmsXA
#
#spring.activemq.broker-url=tcp://127.0.0.1:61616
#spring.activemq.user=user1
#spring.activemq.password=12345
#
#app.stomp.host=127.0.0.1
#app.stomp.port=61614
#app.stomp.login=user1
#app.stomp.pass=12345
#app.stomp.queue-name=jms.queue.CreditRequestsQueue
#
#app.eis.warehouse-jndi=java:/eis/WarehouseConnector
#spring.task.scheduling.pool.size=2
#
#camunda.bpm.history-level=full
#camunda.bpm.auto-deployment-enabled=true
#
## ??????? .properties. ?? ????????
#camunda.bpm.generic-properties.metrics-enabled=false
#logging.level.org.camunda.bpm.engine.impl.cfg=DEBUG
#
#
spring.task.scheduling.pool.size=2

app.eis.warehouse-jndi=java:/eis/WarehouseConnector

app.stomp.host=localhost
app.stomp.port=61614
app.stomp.queue-name=jms.queue.CreditRequestsQueue

app.stomp.login=user1
app.stomp.pass=12345

