# 1. ???? ?????? ????? JNDI (????????? ? WildFly)
spring.datasource.jndi-name=java:jboss/datasources/CitilinkDS

# 2. ??????? ????????? (JTA + JMS)
# ?????????? ??????????? ??? ??????? WildFly ??? ??????????
spring.jms.jndi-name=java:/JmsXA
spring.activemq.broker-url=tcp://127.0.0.1:61716

# ??????????? ??? ???????? (???? ????? ????????????)
spring.activemq.user=user1
spring.activemq.password=12345

# 3. ????????? STOMP (??? ???????? ?????? ? ????)
app.stomp.host=127.0.0.1
app.stomp.port=61713
app.stomp.login=user1
app.stomp.pass=12345
app.stomp.queue-name=jms.queue.CreditRequestsQueue

# 4. ??????????? (?????? ???)
# ???????? ??? ???????, ????? ??????????? ??????? ? ????
spring.task.scheduling.pool.size=2

# 5. JCA ?????????? (?????)
app.eis.warehouse-jndi=java:/eis/WarehouseConnector


